# Generated by Django 3.2.4 on 2021-06-06 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=255)),
                ('read_only', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('token', models.CharField(default=uuid.uuid4, max_length=40)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NamespaceExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('tooltip', models.CharField(blank=True, max_length=1000)),
                ('show_on_explorer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(default='Resource name', max_length=50)),
                ('group', models.CharField(default='General', max_length=50)),
                ('icon', models.CharField(default='icon-aleph', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('params', models.CharField(blank=True, default='{"date": "Date (YYYY-MM-DD)"}', max_length=1000)),
            ],
        ),
    ]
